workflows:
  android-build:
    name: Android Build

    environment:
      java: 17

    scripts:
      - name: Grant Gradle permission
        script: chmod +x gradlew

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
